artifacts_root: artifacts

Data_ingestion:
  root_dir: artifacts/Data_ingestion
  source_URL: https://drive.google.com/file/d/1tBlIaQGXlubpr4Dn_6q3AD0g_ua5hNdx/view?usp=sharing
  local_data_file: artifacts/Data_ingestion/data.zip
  unzip_dir: artifacts/Data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

data_ingestion:
  root_dir: artifacts/Data_ingestion
  source_URL: https://drive.google.com/file/d/1tBlIaQGXlubpr4Dn_6q3AD0g_ua5hNdx/view?usp=sharing
  local_data_file: artifacts/Data_ingestion/data.zip
  unzip_dir: artifacts/Data_ingestion

